### PR TITLE
Generate tests for user secrets and extend timeout to 60mins for test…

### PR DESCRIPTION
**Pull request by ycliuhw**
1. generates tests for user secrets;
2. extends timeout to 60mins for test-secrets_iaas-test-secrets-vault-lxd;
3. sets min juju version for secret related tests;

### CODE REVIEW

**Review by wallyworld — APPROVED** [review]

**Comment by SimonRichardson** [comment]
OT: Is the test doing too much? 60 minutes is a long time!

**Comment by ycliuhw** [comment]
> OT: Is the test doing too much? 60 minutes is a long time!

Because the test deploys vault to machines which takes a very long time to be stablised.

**Comment by SimonRichardson** [comment]
> Because the test deploys vault to machines which takes a very long time to be stablised.

That seems horrendous to run in production.

**Pull request merged**
